---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: master
  namespace: test
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
spec:
  providerConfig:
    value:
      apiVersion: libvirtproviderconfig/v1alpha1
      kind: LibvirtMachineProviderConfig
      domainMemory: 2048
      domainVcpu: 2
      cloudInit:
        isoImagePath: /var/lib/libvirt/images/cloud-init.iso
        userDataSecret: libvirt-actuator-master-userdata-secret
      volume:
        poolName: default
        baseVolumeID: /var/lib/libvirt/images/fedora_base
      networkInterfaceName: default
      networkInterfaceAddress: 192.168.122.0/24
      autostart: false
      uri: {{ .LibvirtURI }}
  versions:
    kubelet: ""
    controlPlane: ""
